import pandas as pd

# ----------------------
# 完整的ICEWS/CAMEO编码数据
# ----------------------
icews_cameo_data = [
    # ----------------------
    # 第一部分：合作类事件 (01-08)
    # ----------------------
    {"层级": "一级", "编码": "01", "英文事件描述": "MAKE PUBLIC STATEMENT", "中文事件描述": "公开发表声明", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "010", "英文事件描述": "Make an uncategorized public statement", "中文事件描述": "发表未分类的通用声明", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "011", "英文事件描述": "Refuse to comment", "中文事件描述": "拒绝发表评论", "Goldstein分值": -0.1, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "012", "英文事件描述": "Make a pessimistic or negative comment", "中文事件描述": "发表悲观/负面评论", "Goldstein分值": -0.4, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "013", "英文事件描述": "Make an optimistic or positive comment", "中文事件描述": "发表乐观/正面评论", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "014", "英文事件描述": "Express intent to consider a policy option", "中文事件描述": "表示考虑某项政策选择", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "015", "英文事件描述": "Acknowledge or claim responsibility", "中文事件描述": "承认/声称对事件负责", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "016", "英文事件描述": "Deny responsibility", "中文事件描述": "否认对事件负责", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "017", "英文事件描述": "Engage in a symbolic act", "中文事件描述": "实施象征性行为", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "018", "英文事件描述": "Make an empathetic comment", "中文事件描述": "发表共情/同情评论", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "019", "英文事件描述": "Express agreement or consensus", "中文事件描述": "表达共识/一致立场", "Goldstein分值": 0.3, "Quad分类": "1-口头合作"},

    {"层级": "一级", "编码": "02", "英文事件描述": "APPEAL", "中文事件描述": "呼吁/请求", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "020", "英文事件描述": "Make an uncategorized appeal", "中文事件描述": "未分类的通用呼吁/请求", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0211", "英文事件描述": "Appeal for economic cooperation", "中文事件描述": "呼吁经济合作", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0212", "英文事件描述": "Appeal for military cooperation", "中文事件描述": "呼吁军事合作", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0213", "英文事件描述": "Appeal for judicial cooperation", "中文事件描述": "呼吁司法合作", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0214", "英文事件描述": "Appeal for intelligence cooperation", "中文事件描述": "呼吁情报合作", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "022", "英文事件描述": "Appeal for diplomatic cooperation", "中文事件描述": "呼吁外交合作（如政策支持）", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0231", "英文事件描述": "Appeal for economic aid", "中文事件描述": "呼吁经济援助", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0232", "英文事件描述": "Appeal for military aid", "中文事件描述": "呼吁军事援助", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0233", "英文事件描述": "Appeal for humanitarian aid", "中文事件描述": "呼吁人道主义援助", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0234", "英文事件描述": "Appeal for military protection or peacekeeping", "中文事件描述": "呼吁军事保护/维和行动", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0241", "英文事件描述": "Appeal for leadership change", "中文事件描述": "呼吁更换领导层", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0242", "英文事件描述": "Appeal for policy change", "中文事件描述": "呼吁政策调整", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0243", "英文事件描述": "Appeal for rights protection", "中文事件描述": "呼吁权利保障", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0244", "英文事件描述": "Appeal for institutional or regime change", "中文事件描述": "呼吁制度/政权变革", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0251", "英文事件描述": "Appeal to ease administrative sanctions", "中文事件描述": "呼吁放宽行政制裁", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0252", "英文事件描述": "Appeal to ease political dissent controls", "中文事件描述": "呼吁放宽政治异议管控", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0253", "英文事件描述": "Appeal to release persons or property", "中文事件描述": "呼吁释放人员/归还财产", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0254", "英文事件描述": "Appeal to ease economic sanctions, boycotts, or embargoes", "中文事件描述": "呼吁放宽经济制裁/抵制/禁运", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0255", "英文事件描述": "Appeal to allow international intervention (not mediation)", "中文事件描述": "呼吁目标方允许国际介入（非调解）", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0256", "英文事件描述": "Appeal to de-escalate military action", "中文事件描述": "呼吁军事行动降级", "Goldstein分值": 0.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "026", "英文事件描述": "Appeal to meet or negotiate", "中文事件描述": "呼吁他方会面/谈判", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "027", "英文事件描述": "Appeal to settle dispute", "中文事件描述": "呼吁他方解决争端", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "028", "英文事件描述": "Appeal to engage in or accept mediation", "中文事件描述": "呼吁开展/接受调解", "Goldstein分值": 0.4, "Quad分类": "1-口头合作"},

    {"层级": "一级", "编码": "03", "英文事件描述": "EXPRESS INTENT TO COOPERATE", "中文事件描述": "表达合作意向", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "030", "英文事件描述": "Express uncategorized intent to cooperate", "中文事件描述": "未分类的通用合作意向表达", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0311", "英文事件描述": "Express intent to engage in economic cooperation", "中文事件描述": "表达经济合作意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0312", "英文事件描述": "Express intent to engage in military cooperation", "中文事件描述": "表达军事合作意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0313", "英文事件描述": "Express intent to engage in judicial cooperation", "中文事件描述": "表达司法合作意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0314", "英文事件描述": "Express intent to engage in intelligence cooperation", "中文事件描述": "表达情报合作意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "032", "英文事件描述": "Express intent to engage in diplomatic cooperation", "中文事件描述": "表达外交合作意向（如政策支持）", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0331", "英文事件描述": "Express intent to provide economic aid", "中文事件描述": "表达提供经济援助的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0332", "英文事件描述": "Express intent to provide military aid", "中文事件描述": "表达提供军事援助的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0333", "英文事件描述": "Express intent to provide humanitarian aid", "中文事件描述": "表达提供人道主义援助的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0334", "英文事件描述": "Express intent to provide military protection or peacekeeping", "中文事件描述": "表达提供军事保护/维和的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0341", "英文事件描述": "Express intent to implement leadership change", "中文事件描述": "表达实施领导层调整的意向", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0342", "英文事件描述": "Express intent to implement policy change", "中文事件描述": "表达实施政策调整的意向", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0343", "英文事件描述": "Express intent to implement rights protection", "中文事件描述": "表达保障权利的意向", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0344", "英文事件描述": "Express intent to implement institutional or regime change", "中文事件描述": "表达实施制度/政权变革的意向", "Goldstein分值": 1.0, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0351", "英文事件描述": "Express intent to ease administrative sanctions", "中文事件描述": "表达放宽行政制裁的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0352", "英文事件描述": "Express intent to ease political dissent controls", "中文事件描述": "表达放宽政治异议管控的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0353", "英文事件描述": "Express intent to release persons or property", "中文事件描述": "表达释放人员/归还财产的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0354", "英文事件描述": "Express intent to ease economic sanctions, boycotts, or embargoes", "中文事件描述": "表达放宽经济制裁/抵制/禁运的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0355", "英文事件描述": "Express intent to allow international intervention (not mediation)", "中文事件描述": "表达允许国际介入（非调解）的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "四级", "编码": "0356", "英文事件描述": "Express intent to de-escalate military action", "中文事件描述": "表达军事行动降级的意向", "Goldstein分值": 1.5, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "036", "英文事件描述": "Express intent to meet or negotiate", "中文事件描述": "表达会面/谈判的意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "037", "英文事件描述": "Express intent to settle dispute", "中文事件描述": "表达解决争端的意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "038", "英文事件描述": "Express intent to accept mediation", "中文事件描述": "表达接受调解的意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},
    {"层级": "三级", "编码": "039", "英文事件描述": "Express intent to engage in mediation", "中文事件描述": "表达开展调解的意向", "Goldstein分值": 1.2, "Quad分类": "1-口头合作"},

    {"层级": "一级", "编码": "04", "英文事件描述": "CONSULT", "中文事件描述": "协商/磋商", "Goldstein分值": 1.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "040", "英文事件描述": "Engage in uncategorized consultation", "中文事件描述": "未分类的通用协商行为", "Goldstein分值": 1.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "041", "英文事件描述": "Consult by telephone", "中文事件描述": "电话磋商", "Goldstein分值": 1.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "042", "英文事件描述": "Make a visit", "中文事件描述": "出访", "Goldstein分值": 1.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "043", "英文事件描述": "Receive a visit", "中文事件描述": "接待来访", "Goldstein分值": 1.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "044", "英文事件描述": "Meet at a third location", "中文事件描述": "在第三方地点会面", "Goldstein分值": 1.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "045", "英文事件描述": "Engage in mediation", "中文事件描述": "开展调解", "Goldstein分值": 1.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "046", "英文事件描述": "Engage in negotiations", "中文事件描述": "开展谈判", "Goldstein分值": 1.8, "Quad分类": "2-实质合作"},

    {"层级": "一级", "编码": "05", "英文事件描述": "ENGAGE IN DIPLOMATIC COOPERATION", "中文事件描述": "开展外交合作", "Goldstein分值": 3.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "050", "英文事件描述": "Engage in uncategorized diplomatic cooperation", "中文事件描述": "未分类的通用外交合作", "Goldstein分值": 3.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "051", "英文事件描述": "Praise, support, or endorse", "中文事件描述": "赞扬/支持/背书", "Goldstein分值": 3.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "052", "英文事件描述": "Defend or verbally support", "中文事件描述": "口头辩护/声援", "Goldstein分值": 3.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "053", "英文事件描述": "Mobilize support for the target", "中文事件描述": "为对方召集支持", "Goldstein分值": 3.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "054", "英文事件描述": "Grant diplomatic recognition", "中文事件描述": "给予外交承认", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "055", "英文事件描述": "Apologize", "中文事件描述": "道歉", "Goldstein分值": 4.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "056", "英文事件描述": "Forgive or pardon", "中文事件描述": "宽恕/谅解", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "057", "英文事件描述": "Sign a formal agreement", "中文事件描述": "签署正式协议", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},

    {"层级": "一级", "编码": "06", "英文事件描述": "ENGAGE IN MATERIAL COOPERATION", "中文事件描述": "开展实质合作", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "060", "英文事件描述": "Engage in uncategorized material cooperation", "中文事件描述": "未分类的通用实质合作", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "061", "英文事件描述": "Engage in economic cooperation", "中文事件描述": "开展经济合作", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "062", "英文事件描述": "Engage in military cooperation", "中文事件描述": "开展军事合作", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "063", "英文事件描述": "Engage in judicial cooperation", "中文事件描述": "开展司法合作", "Goldstein分值": 5.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "064", "英文事件描述": "Share intelligence or information", "中文事件描述": "共享情报/信息", "Goldstein分值": 5.5, "Quad分类": "2-实质合作"},

    {"层级": "一级", "编码": "07", "英文事件描述": "PROVIDE AID", "中文事件描述": "提供援助", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "070", "英文事件描述": "Provide uncategorized aid", "中文事件描述": "未分类的通用援助", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "071", "英文事件描述": "Provide economic aid", "中文事件描述": "提供经济援助", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "072", "英文事件描述": "Provide military aid", "中文事件描述": "提供军事援助", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "073", "英文事件描述": "Provide humanitarian aid", "中文事件描述": "提供人道主义援助", "Goldstein分值": 7.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "074", "英文事件描述": "Provide military protection or peacekeeping", "中文事件描述": "提供军事保护/维和行动", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "075", "英文事件描述": "Grant asylum", "中文事件描述": "给予庇护", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},

    {"层级": "一级", "编码": "08", "英文事件描述": "YIELD", "中文事件描述": "妥协/让步", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "080", "英文事件描述": "Make an uncategorized yield", "中文事件描述": "未分类的通用妥协/让步", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0811", "英文事件描述": "Ease restrictions on political freedoms", "中文事件描述": "放宽政治自由限制", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0812", "英文事件描述": "Lift bans on political parties or politicians", "中文事件描述": "解除对政党/政客的禁令", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0813", "英文事件描述": "Lift a curfew", "中文事件描述": "解除宵禁", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0814", "英文事件描述": "Lift a state of emergency or martial law", "中文事件描述": "解除紧急状态/戒严令", "Goldstein分值": 5.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "082", "英文事件描述": "Ease political dissent controls", "中文事件描述": "放宽政治异议管控", "Goldstein分值": 4.5, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0831", "英文事件描述": "Accede to demands for leadership change", "中文事件描述": "同意更换领导层的诉求", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0832", "英文事件描述": "Accede to demands for policy change", "中文事件描述": "同意政策调整的诉求", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0833", "英文事件描述": "Accede to demands for rights protection", "中文事件描述": "同意权利保障的诉求", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0834", "英文事件描述": "Accede to demands for institutional or regime change", "中文事件描述": "同意制度/政权变革的诉求", "Goldstein分值": 4.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0841", "英文事件描述": "Release or return persons", "中文事件描述": "归还/释放人员", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0842", "英文事件描述": "Release or return property", "中文事件描述": "归还/释放财产", "Goldstein分值": 4.5, "Quad分类": "2-实质合作"},
    {"层级": "三级", "编码": "085", "英文事件描述": "Ease economic sanctions, boycotts, or embargoes", "中文事件描述": "放宽经济制裁/抵制/禁运", "Goldstein分值": 5.5, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0861", "英文事件描述": "Accept deployment of peacekeeping forces", "中文事件描述": "接受维和部队部署", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0862", "英文事件描述": "Accept entry of inspectors or observers", "中文事件描述": "接受核查人员入境", "Goldstein分值": 4.5, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0863", "英文事件描述": "Allow humanitarian access", "中文事件描述": "允许人道主义通道", "Goldstein分值": 5.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0871", "英文事件描述": "Announce a truce or ceasefire", "中文事件描述": "宣布休战/停火", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0872", "英文事件描述": "Lift a military blockade", "中文事件描述": "解除军事封锁", "Goldstein分值": 6.0, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0873", "英文事件描述": "Demobilize armed forces", "中文事件描述": "武装力量复员", "Goldstein分值": 6.5, "Quad分类": "2-实质合作"},
    {"层级": "四级", "编码": "0874", "英文事件描述": "Retreat or surrender militarily", "中文事件描述": "军事撤退/投降", "Goldstein分值": 7.0, "Quad分类": "2-实质合作"},

    # ----------------------
    # 第二部分：中性调查类 (09)
    # ----------------------
    {"层级": "一级", "编码": "09", "英文事件描述": "INVESTIGATE", "中文事件描述": "调查", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "090", "英文事件描述": "Engage in an uncategorized investigation", "中文事件描述": "未分类的通用调查行为", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "091", "英文事件描述": "Investigate crime or corruption", "中文事件描述": "调查犯罪/腐败行为", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "092", "英文事件描述": "Investigate human rights abuses", "中文事件描述": "调查人权侵犯行为", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "093", "英文事件描述": "Investigate military actions", "中文事件描述": "调查军事行动", "Goldstein分值": -2.2, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "094", "英文事件描述": "Investigate war crimes", "中文事件描述": "调查战争罪行", "Goldstein分值": -2.5, "Quad分类": "3-口头冲突"},

    # ----------------------
    # 第三部分：冲突类事件 (10-20)
    # ----------------------
    {"层级": "一级", "编码": "10", "英文事件描述": "DEMAND", "中文事件描述": "要求/通牒", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "100", "英文事件描述": "Make an uncategorized demand", "中文事件描述": "未分类的通用要求", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1011", "英文事件描述": "Demand economic cooperation", "中文事件描述": "要求经济合作", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1012", "英文事件描述": "Demand military cooperation", "中文事件描述": "要求军事合作", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1013", "英文事件描述": "Demand judicial cooperation", "中文事件描述": "要求司法合作", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1014", "英文事件描述": "Demand intelligence cooperation", "中文事件描述": "要求情报合作", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "102", "英文事件描述": "Demand diplomatic cooperation", "中文事件描述": "要求外交合作（如政策支持）", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1031", "英文事件描述": "Demand economic aid", "中文事件描述": "要求经济援助", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1032", "英文事件描述": "Demand military aid", "中文事件描述": "要求军事援助", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1033", "英文事件描述": "Demand humanitarian aid", "中文事件描述": "要求人道主义援助", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1034", "英文事件描述": "Demand military protection or peacekeeping", "中文事件描述": "要求军事保护/维和行动", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1041", "英文事件描述": "Demand leadership change", "中文事件描述": "要求更换领导层", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1042", "英文事件描述": "Demand policy change", "中文事件描述": "要求政策调整", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1043", "英文事件描述": "Demand rights protection", "中文事件描述": "要求权利保障", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1044", "英文事件描述": "Demand institutional or regime change", "中文事件描述": "要求制度/政权变革", "Goldstein分值": -5.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1051", "英文事件描述": "Demand to ease administrative sanctions", "中文事件描述": "要求放宽行政制裁", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1052", "英文事件描述": "Demand to ease political dissent controls", "中文事件描述": "要求放宽政治异议管控", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1053", "英文事件描述": "Demand to release persons or property", "中文事件描述": "要求释放人员/归还财产", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1054", "英文事件描述": "Demand to ease economic sanctions, boycotts, or embargoes", "中文事件描述": "要求放宽经济制裁/抵制/禁运", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1055", "英文事件描述": "Demand to allow international intervention (not mediation)", "中文事件描述": "要求目标方允许国际介入（非调解）", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1056", "英文事件描述": "Demand to de-escalate military action", "中文事件描述": "要求军事行动降级", "Goldstein分值": -4.8, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "106", "英文事件描述": "Demand to meet or negotiate", "中文事件描述": "要求会面/谈判", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "107", "英文事件描述": "Demand to settle dispute", "中文事件描述": "要求解决争端", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "108", "英文事件描述": "Demand to engage in mediation", "中文事件描述": "要求开展调解", "Goldstein分值": -4.5, "Quad分类": "3-口头冲突"},

    {"层级": "一级", "编码": "11", "英文事件描述": "DISAPPROVE", "中文事件描述": "反对/不认可", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "110", "英文事件描述": "Make an uncategorized disapproval", "中文事件描述": "未分类的通用反对行为", "Goldstein分值": -2.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "111", "英文事件描述": "Criticize or denounce", "中文事件描述": "批评/谴责", "Goldstein分值": -2.2, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1121", "英文事件描述": "Accuse of crime or corruption", "中文事件描述": "指控犯罪/腐败", "Goldstein分值": -2.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1122", "英文事件描述": "Accuse of human rights abuses", "中文事件描述": "指控人权侵犯", "Goldstein分值": -2.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1123", "英文事件描述": "Accuse of aggression", "中文事件描述": "指控侵略行为", "Goldstein分值": -2.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1124", "英文事件描述": "Accuse of war crimes", "中文事件描述": "指控战争罪行", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1125", "英文事件描述": "Accuse of espionage or treason", "中文事件描述": "指控间谍/叛国行为", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "113", "英文事件描述": "Mobilize opposition against the target", "中文事件描述": "召集对目标方的反对力量", "Goldstein分值": -2.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "114", "英文事件描述": "Make a formal complaint or protest", "中文事件描述": "正式投诉/抗议", "Goldstein分值": -2.8, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "115", "英文事件描述": "Initiate legal proceedings", "中文事件描述": "提起法律诉讼", "Goldstein分值": -2.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "116", "英文事件描述": "Find guilty or impose legal responsibility", "中文事件描述": "判定有罪/承担法律责任", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},

    {"层级": "一级", "编码": "12", "英文事件描述": "REJECT", "中文事件描述": "拒绝", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "120", "英文事件描述": "Make an uncategorized rejection", "中文事件描述": "未分类的通用拒绝行为", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1211", "英文事件描述": "Reject economic cooperation", "中文事件描述": "拒绝经济合作", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1212", "英文事件描述": "Reject military cooperation", "中文事件描述": "拒绝军事合作", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1221", "英文事件描述": "Reject a request for economic aid", "中文事件描述": "拒绝经济援助请求", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1222", "英文事件描述": "Reject a request for military aid", "中文事件描述": "拒绝军事援助请求", "Goldstein分值": -3.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1223", "英文事件描述": "Reject a request for humanitarian aid", "中文事件描述": "拒绝人道主义援助请求", "Goldstein分值": -3.2, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1224", "英文事件描述": "Reject a request for military protection or peacekeeping", "中文事件描述": "拒绝军事保护/维和请求", "Goldstein分值": -3.2, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1231", "英文事件描述": "Reject demands for leadership change", "中文事件描述": "拒绝更换领导层的诉求", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1232", "英文事件描述": "Reject demands for policy change", "中文事件描述": "拒绝政策调整的诉求", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1233", "英文事件描述": "Reject demands for rights protection", "中文事件描述": "拒绝权利保障的诉求", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1234", "英文事件描述": "Reject demands for institutional or regime change", "中文事件描述": "拒绝制度/政权变革的诉求", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1241", "英文事件描述": "Reject demands to ease administrative sanctions", "中文事件描述": "拒绝放宽行政制裁", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1242", "英文事件描述": "Reject demands to ease political dissent controls", "中文事件描述": "拒绝放宽政治异议管控", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1243", "英文事件描述": "Reject demands to release persons or property", "中文事件描述": "拒绝释放人员/归还财产", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1244", "英文事件描述": "Reject demands to ease economic sanctions, boycotts, or embargoes", "中文事件描述": "拒绝放宽经济制裁/抵制/禁运", "Goldstein分值": -3.8, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1245", "英文事件描述": "Reject demands to allow international intervention", "中文事件描述": "拒绝允许国际介入", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1246", "英文事件描述": "Reject demands to de-escalate military action", "中文事件描述": "拒绝军事行动降级", "Goldstein分值": -4.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "125", "英文事件描述": "Reject a proposal to meet, discuss, or negotiate", "中文事件描述": "拒绝会面/讨论/谈判提议", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "126", "英文事件描述": "Reject mediation", "中文事件描述": "拒绝调解", "Goldstein分值": -3.8, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "127", "英文事件描述": "Reject a dispute settlement or agreement", "中文事件描述": "拒绝争端解决方案/协议", "Goldstein分值": -4.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "128", "英文事件描述": "Violate a norm or law", "中文事件描述": "违反规范/法律", "Goldstein分值": -3.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "129", "英文事件描述": "Veto", "中文事件描述": "否决", "Goldstein分值": -4.0, "Quad分类": "3-口头冲突"},

    {"层级": "一级", "编码": "13", "英文事件描述": "THREATEN", "中文事件描述": "威胁", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "130", "英文事件描述": "Make an uncategorized threat", "中文事件描述": "未分类的通用威胁行为", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1311", "英文事件描述": "Threaten to reduce or stop aid", "中文事件描述": "威胁减少/停止援助", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1312", "英文事件描述": "Threaten to impose sanctions, boycotts, or embargoes", "中文事件描述": "威胁实施制裁/抵制/禁运", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1313", "英文事件描述": "Threaten to reduce or break diplomatic relations", "中文事件描述": "威胁降低/断绝外交关系", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1321", "英文事件描述": "Threaten to restrict political freedoms", "中文事件描述": "威胁限制政治自由", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1322", "英文事件描述": "Threaten to ban political parties or politicians", "中文事件描述": "威胁取缔政党/政客", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1323", "英文事件描述": "Threaten to impose a curfew", "中文事件描述": "威胁实施宵禁", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1324", "英文事件描述": "Threaten to impose a state of emergency or martial law", "中文事件描述": "威胁实施紧急状态/戒严令", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "133", "英文事件描述": "Threaten to mobilize political dissent or protest", "中文事件描述": "威胁发起政治异议/抗议", "Goldstein分值": -6.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "134", "英文事件描述": "Threaten to terminate negotiations", "中文事件描述": "威胁终止谈判", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "135", "英文事件描述": "Threaten to terminate mediation", "中文事件描述": "威胁终止调解", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "136", "英文事件描述": "Threaten to terminate international intervention", "中文事件描述": "威胁终止国际介入", "Goldstein分值": -6.5, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "137", "英文事件描述": "Threaten to impose repression", "中文事件描述": "威胁实施镇压", "Goldstein分值": -7.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1381", "英文事件描述": "Threaten to impose a blockade", "中文事件描述": "威胁实施封锁", "Goldstein分值": -7.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1382", "英文事件描述": "Threaten to occupy territory", "中文事件描述": "威胁实施占领", "Goldstein分值": -7.5, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1383", "英文事件描述": "Threaten to use unconventional violence", "中文事件描述": "威胁实施非常规暴力", "Goldstein分值": -8.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1384", "英文事件描述": "Threaten to use conventional military force", "中文事件描述": "威胁实施常规军事打击", "Goldstein分值": -8.0, "Quad分类": "3-口头冲突"},
    {"层级": "四级", "编码": "1385", "英文事件描述": "Threaten to use weapons of mass destruction", "中文事件描述": "威胁使用大规模杀伤性武器", "Goldstein分值": -9.0, "Quad分类": "3-口头冲突"},
    {"层级": "三级", "编码": "139", "英文事件描述": "Issue an ultimatum", "中文事件描述": "发出最后通牒", "Goldstein分值": -7.5, "Quad分类": "3-口头冲突"},

    {"层级": "一级", "编码": "14", "英文事件描述": "PROTEST", "中文事件描述": "抗议", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "140", "英文事件描述": "Engage in uncategorized political dissent", "中文事件描述": "未分类的通用政治异议行为", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1411", "英文事件描述": "Demonstrate for leadership change", "中文事件描述": "为更换领导层举行示威集会", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1412", "英文事件描述": "Demonstrate for policy change", "中文事件描述": "为政策调整举行示威集会", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1413", "英文事件描述": "Demonstrate for rights protection", "中文事件描述": "为权利保障举行示威集会", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1414", "英文事件描述": "Demonstrate for institutional or regime change", "中文事件描述": "为制度/政权变革举行示威集会", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1421", "英文事件描述": "Conduct a hunger strike for leadership change", "中文事件描述": "为更换领导层举行绝食抗议", "Goldstein分值": -6.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1422", "英文事件描述": "Conduct a hunger strike for policy change", "中文事件描述": "为政策调整举行绝食抗议", "Goldstein分值": -6.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1423", "英文事件描述": "Conduct a hunger strike for rights protection", "中文事件描述": "为权利保障举行绝食抗议", "Goldstein分值": -6.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1424", "英文事件描述": "Conduct a hunger strike for institutional or regime change", "中文事件描述": "为制度/政权变革举行绝食抗议", "Goldstein分值": -6.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1431", "英文事件描述": "Conduct a strike or boycott for leadership change", "中文事件描述": "为更换领导层举行罢工/抵制", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1432", "英文事件描述": "Conduct a strike or boycott for policy change", "中文事件描述": "为政策调整举行罢工/抵制", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1433", "英文事件描述": "Conduct a strike or boycott for rights protection", "中文事件描述": "为权利保障举行罢工/抵制", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1434", "英文事件描述": "Conduct a strike or boycott for institutional or regime change", "中文事件描述": "为制度/政权变革举行罢工/抵制", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1441", "英文事件描述": "Block passage for leadership change", "中文事件描述": "为更换领导层封锁通道", "Goldstein分值": -6.8, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1442", "英文事件描述": "Block passage for policy change", "中文事件描述": "为政策调整封锁通道", "Goldstein分值": -6.8, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1443", "英文事件描述": "Block passage for rights protection", "中文事件描述": "为权利保障封锁通道", "Goldstein分值": -6.8, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1444", "英文事件描述": "Block passage for institutional or regime change", "中文事件描述": "为制度/政权变革封锁通道", "Goldstein分值": -6.8, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1451", "英文事件描述": "Engage in violent protest or riot for leadership change", "中文事件描述": "为更换领导层发起暴力抗议/骚乱", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1452", "英文事件描述": "Engage in violent protest or riot for policy change", "中文事件描述": "为政策调整发起暴力抗议/骚乱", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1453", "英文事件描述": "Engage in violent protest or riot for rights protection", "中文事件描述": "为权利保障发起暴力抗议/骚乱", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1454", "英文事件描述": "Engage in violent protest or riot for institutional or regime change", "中文事件描述": "为制度/政权变革发起暴力抗议/骚乱", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "15", "英文事件描述": "EXHIBIT FORCE POSTURE", "中文事件描述": "展示军事姿态", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "150", "英文事件描述": "Exhibit an uncategorized military or police force posture", "中文事件描述": "未分类的通用军事/警察力量展示", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "151", "英文事件描述": "Raise police alert status", "中文事件描述": "提升警察警戒状态", "Goldstein分值": -6.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "152", "英文事件描述": "Raise military alert status", "中文事件描述": "提升军事警戒状态", "Goldstein分值": -6.8, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "153", "英文事件描述": "Mobilize or increase police forces", "中文事件描述": "动员/增强警察力量", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "154", "英文事件描述": "Mobilize or increase armed forces", "中文事件描述": "动员/增强武装力量", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "155", "英文事件描述": "Mobilize or increase cyber forces", "中文事件描述": "动员/增强网络力量", "Goldstein分值": -6.5, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "16", "英文事件描述": "REDUCE RELATIONS", "中文事件描述": "降低双边关系", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "160", "英文事件描述": "Engage in an uncategorized reduction of relations", "中文事件描述": "未分类的通用关系降级行为", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "161", "英文事件描述": "Reduce or break diplomatic relations", "中文事件描述": "降低/断绝外交关系", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1621", "英文事件描述": "Reduce or stop economic aid", "中文事件描述": "减少/停止经济援助", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1622", "英文事件描述": "Reduce or stop military aid", "中文事件描述": "减少/停止军事援助", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1623", "英文事件描述": "Reduce or stop humanitarian aid", "中文事件描述": "减少/停止人道主义援助", "Goldstein分值": -7.2, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "163", "英文事件描述": "Impose an embargo, boycott, or sanctions", "中文事件描述": "实施禁运/抵制/制裁", "Goldstein分值": -8.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "164", "英文事件描述": "Terminate negotiations", "中文事件描述": "终止谈判", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "165", "英文事件描述": "Terminate mediation", "中文事件描述": "终止调解", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1661", "英文事件描述": "Expel or withdraw peacekeepers", "中文事件描述": "驱逐/撤回维和人员", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1662", "英文事件描述": "Expel or withdraw inspectors or observers", "中文事件描述": "驱逐/撤回核查/观察人员", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1663", "英文事件描述": "Expel or withdraw aid agencies", "中文事件描述": "驱逐/撤回援助机构", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "17", "英文事件描述": "COERCE", "中文事件描述": "胁迫/强制", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "170", "英文事件描述": "Engage in an uncategorized coercion", "中文事件描述": "未分类的通用胁迫行为", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1711", "英文事件描述": "Seize property", "中文事件描述": "没收财产", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1712", "英文事件描述": "Destroy property", "中文事件描述": "破坏财产", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1721", "英文事件描述": "Impose restrictions on political freedoms", "中文事件描述": "实施政治自由限制", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1722", "英文事件描述": "Ban political parties or politicians", "中文事件描述": "取缔政党/政客", "Goldstein分值": -7.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1723", "英文事件描述": "Impose a curfew", "中文事件描述": "实施宵禁", "Goldstein分值": -7.2, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1724", "英文事件描述": "Impose a state of emergency or martial law", "中文事件描述": "实施紧急状态/戒严令", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "173", "英文事件描述": "Arrest, detain, or charge with legal action", "中文事件描述": "逮捕/拘留/提起法律指控", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "174", "英文事件描述": "Expel or deport individuals", "中文事件描述": "驱逐/遣返个人", "Goldstein分值": -7.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "175", "英文事件描述": "Use violent repressive tactics", "中文事件描述": "实施暴力镇压手段", "Goldstein分值": -8.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "176", "英文事件描述": "Launch a cyber attack", "中文事件描述": "发起网络攻击", "Goldstein分值": -7.5, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "18", "英文事件描述": "ASSAULT", "中文事件描述": "攻击", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "180", "英文事件描述": "Engage in an uncategorized unconventional violence", "中文事件描述": "未分类的通用非常规暴力行为", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "181", "英文事件描述": "Kidnap, hijack, or take hostage", "中文事件描述": "绑架/劫持/扣为人质", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1821", "英文事件描述": "Commit sexual assault", "中文事件描述": "性侵犯", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1822", "英文事件描述": "Commit torture", "中文事件描述": "酷刑", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1823", "英文事件描述": "Commit physical assault resulting in death", "中文事件描述": "人身攻击致死", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1831", "英文事件描述": "Commit a suicide bombing", "中文事件描述": "实施自杀式爆炸", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1832", "英文事件描述": "Commit a car bombing", "中文事件描述": "实施汽车爆炸", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1833", "英文事件描述": "Commit a roadside bombing", "中文事件描述": "实施路边爆炸", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1834", "英文事件描述": "Commit a bombing at a fixed target", "中文事件描述": "实施定点场所爆炸", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "184", "英文事件描述": "Use human shields", "中文事件描述": "用作人盾", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "185", "英文事件描述": "Attempt an assassination", "中文事件描述": "暗杀未遂", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "186", "英文事件描述": "Carry out an assassination", "中文事件描述": "暗杀成功", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "19", "英文事件描述": "FIGHT", "中文事件描述": "交战", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "190", "英文事件描述": "Engage in an uncategorized use of conventional military force", "中文事件描述": "未分类的通用常规军事力量使用", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "191", "英文事件描述": "Impose a blockade or restrict passage", "中文事件描述": "实施封锁/限制通行", "Goldstein分值": -8.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "192", "英文事件描述": "Occupy territory", "中文事件描述": "占领领土", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "193", "英文事件描述": "Engage in small arms fire", "中文事件描述": "轻武器交火", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "194", "英文事件描述": "Engage in artillery or tank fire", "中文事件描述": "火炮/坦克交火", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1951", "英文事件描述": "Use precision-guided aerial weapons", "中文事件描述": "使用精确制导空中武器", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "1952", "英文事件描述": "Use remotely piloted aerial weapons (drones)", "中文事件描述": "使用远程操控空中武器（无人机）", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "196", "英文事件描述": "Violate a ceasefire agreement", "中文事件描述": "违反停火协议", "Goldstein分值": -9.0, "Quad分类": "4-实质冲突"},

    {"层级": "一级", "编码": "20", "英文事件描述": "USE UNCONVENTIONAL MASS VIOLENCE", "中文事件描述": "使用非常规大规模暴力", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "200", "英文事件描述": "Engage in an uncategorized unconventional mass violence", "中文事件描述": "未分类的通用非常规大规模暴力", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "201", "英文事件描述": "Engage in mass expulsion", "中文事件描述": "实施大规模驱逐", "Goldstein分值": -9.5, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "202", "英文事件描述": "Engage in mass killing", "中文事件描述": "实施大规模屠杀", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
    {"层级": "三级", "编码": "203", "英文事件描述": "Engage in ethnic cleansing", "中文事件描述": "实施种族清洗", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "2041", "英文事件描述": "Use chemical, biological, or radiological weapons", "中文事件描述": "使用化学/生物/放射性武器", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
    {"层级": "四级", "编码": "2042", "英文事件描述": "Detonate a nuclear weapon", "中文事件描述": "引爆核武器", "Goldstein分值": -10.0, "Quad分类": "4-实质冲突"},
]

# ----------------------
# 生成DataFrame并导出CSV
# ----------------------
df = pd.DataFrame(icews_cameo_data)

# 按编码顺序排序，确保整齐
df['编码长度'] = df['编码'].str.len()
df = df.sort_values(by=['编码长度', '编码']).drop(columns=['编码长度'])

# 导出CSV，使用utf-8-sig防止Excel中文乱码
# 注意：路径前加 r 表示原始字符串，避免反斜杠转义问题
output_file = r"C:\Users\胡克劳\Desktop\ICEWS\ICEWS_CAMEO_事件编码体系完整表.csv"
df.to_csv(output_file, index=False, encoding='utf-8-sig')

print(f"CSV文件已成功生成：{output_file}")
print("文件包含字段：层级、编码、英文事件描述、中文事件描述、Goldstein分值、Quad分类")
