import pandas as pd
import os

# 完整数据列表（保持原有数据不变）
data = [
    ["01", "MAKE PUBLIC STATEMENT", "发表公开声明"],
    ["010", "Make statement, not specified below", "发表未特指声明"],
    ["011", "Decline comment", "拒绝置评"],
    ["012", "Make pessimistic comment", "发表悲观评论"],
    ["013", "Make optimistic comment", "发表乐观评论"],
    ["014", "Consider policy option", "考虑政策选择"],
    ["015", "Acknowledge or claim responsibility", "承认或声称责任"],
    ["016", "Deny responsibility", "否认责任"],
    ["017", "Engage in symbolic act", "参与象征性行动"],
    ["018", "Make empathetic comment", "发表同情性评论"],
    ["019", "Express accord", "表达一致"],
    ["02", "APPEAL", "呼吁"],
    ["020", "Appeal, not specified below", "呼吁，未特指"],
    ["021", "Appeal for material cooperation", "呼吁物质合作"],
    ["0211", "Appeal for economic cooperation", "呼吁经济合作"],
    ["0212", "Appeal for military cooperation", "呼吁军事合作"],
    ["022", "Appeal for diplomatic cooperation", "呼吁外交合作"],
    ["023", "Appeal for aid", "呼吁援助"],
    ["0231", "Appeal for economic aid", "呼吁经济援助"],
    ["0232", "Appeal for military aid", "呼吁军事援助"],
    ["0233", "Appeal for humanitarian aid", "呼吁人道主义援助"],
    ["024", "Appeal for political reform", "呼吁政治改革"],
    ["0241", "Appeal for change in leadership", "呼吁领导层变更"],
    ["0242", "Appeal for policy change", "呼吁政策变更"],
    ["0243", "Appeal for rights", "呼吁权利"],
    ["025", "Appeal to yield", "呼吁让步"],
    ["0251", "Appeal for easing of administrative sanctions", "呼吁放松行政制裁"],
    ["03", "EXPRESS INTENT TO COOPERATE", "表达合作意向"],
    ["030", "Express intent to cooperate, not specified below", "表达合作意向，未特指"],
    ["031", "Express intent to meet or negotiate", "表达会面或谈判意向"],
    ["032", "Express intent to yield", "表达让步意向"],
    ["033", "Express intent to settle dispute", "表达解决争端意向"],
    ["04", "CONSULT", "磋商"],
    ["040", "Consult, not specified below", "磋商，未特指"],
    ["041", "Engage in diplomatic consultation", "开展外交磋商"],
    ["042", "Engage in other consultation", "开展其他磋商"],
    ["05", "ENGAGE IN DIPLOMATIC COOPERATION", "开展外交合作"],
    ["050", "Engage in diplomatic cooperation, not specified below", "开展外交合作，未特指"],
    ["051", "Praise/endorse", "赞扬/支持"],
    ["052", "Defend", "辩护"],
    ["053", "Rally support/Call for support", "召集支持/呼吁支持"],
    ["054", "Rally for support (demonstration)", "举行支持集会（示威）"],
    ["055", "Host a visit", "主办访问"],
    ["056", "Visit a foreign country", "出访外国"],
    ["057", "Return a visit", "回访"],
    ["058", "Expel an individual or group", "驱逐个人或团体"],
    ["06", "ENGAGE IN MATERIAL COOPERATION", "开展物质合作"],
    ["060", "Engage in material cooperation, not specified below", "开展物质合作，未特指"],
    ["061", "Provide economic aid", "提供经济援助"],
    ["062", "Provide military aid", "提供军事援助"],
    ["063", "Provide humanitarian aid", "提供人道主义援助"],
    ["064", "Grant diplomatic recognition", "给予外交承认"],
    ["065", "Establish diplomatic relations", "建立外交关系"],
    ["066", "Sign a treaty", "签署条约"],
    ["07", "PROVIDE AID", "提供援助"],
    ["070", "Provide aid, not specified below", "提供援助，未特指"],
    ["071", "Provide economic aid", "提供经济援助"],
    ["072", "Provide military aid", "提供军事援助"],
    ["073", "Provide humanitarian aid", "提供人道主义援助"],
    ["08", "YIELD", "让步"],
    ["080", "Yield, not specified below", "让步，未特指"],
    ["081", "Ease administrative sanctions", "放松行政制裁"],
    ["082", "Ease popular dissent", "缓和民众不满"],
    ["083", "Accept responsibility", "承担责任"],
    ["084", "Retract an accusation or statement", "撤回指控或声明"],
    ["085", "Apologize", "道歉"],
    ["086", "Comply with international law or UN resolution", "遵守国际法或联合国决议"],
    ["09", "INVESTIGATE", "调查"],
    ["090", "Investigate, not specified below", "调查，未特指"],
    ["091", "Investigate crime or corruption", "调查犯罪或腐败"],
    ["092", "Investigate human rights abuses", "调查侵犯人权行为"],
    ["10", "DEMAND", "要求"],
    ["100", "Demand, not specified below", "要求，未特指"],
    ["101", "Demand material cooperation", "要求物质合作"],
    ["102", "Demand diplomatic cooperation", "要求外交合作"],
    ["103", "Demand aid", "要求援助"],
    ["104", "Demand political reform", "要求政治改革"],
    ["105", "Demand yield", "要求让步"],
    ["11", "DISAPPROVE", "反对"],
    ["110", "Disapprove, not specified below", "反对，未特指"],
    ["111", "Criticize or denounce", "批评或谴责"],
    ["112", "Accuse", "指控"],
    ["113", "Blame", "指责"],
    ["12", "REJECT", "拒绝"],
    ["120", "Reject, not specified below", "拒绝，未特指"],
    ["121", "Reject material cooperation", "拒绝物质合作"],
    ["122", "Reject diplomatic cooperation", "拒绝外交合作"],
    ["123", "Reject aid", "拒绝援助"],
    ["124", "Reject political reform", "拒绝政治改革"],
    ["125", "Reject demand", "拒绝要求"],
    ["13", "THREATEN", "威胁"],
    ["130", "Threaten, not specified below", "威胁，未特指"],
    ["131", "Threaten with military force", "以武力威胁"],
    ["132", "Threaten with economic sanctions", "以经济制裁威胁"],
    ["133", "Threaten with diplomatic pressure", "以外交压力威胁"],
    ["134", "Threaten with boycott or embargo", "以抵制或禁运威胁"],
    ["14", "PROTEST", "抗议"],
    ["140", "Protest, not specified below", "抗议，未特指"],
    ["141", "Conduct a hunger strike", "进行绝食抗议"],
    ["142", "Conduct a strike or walkout", "进行罢工或停工"],
    ["143", "Conduct a demonstration or rally", "进行示威或集会"],
    ["144", "Conduct a riot or violent protest", "进行骚乱或暴力抗议"],
    ["15", "EXHIBIT FORCE POSTURE", "展示武力姿态"],
    ["150", "Exhibit force posture, not specified below", "展示武力姿态，未特指"],
    ["151", "Mobilize or deploy military forces", "动员或部署军事力量"],
    ["152", "Conduct military exercises", "进行军事演习"],
    ["153", "Conduct a show of force", "进行武力展示"],
    ["16", "REDUCE RELATIONS", "降低关系"],
    ["160", "Reduce relations, not specified below", "降低关系，未特指"],
    ["161", "Reduce or break diplomatic relations", "降低或断绝外交关系"],
    ["162", "Impose economic sanctions", "实施经济制裁"],
    ["163", "Impose embargo or boycott", "实施禁运或抵制"],
    ["164", "Expel diplomats", "驱逐外交官"],
    ["17", "COERCE", "胁迫"],
    ["170", "Coerce, not specified below", "胁迫，未特指"],
    ["171", "Seize property or assets", "扣押财产或资产"],
    ["172", "Impose a blockade", "实施封锁"],
    ["173", "Occupy territory", "占领领土"],
    ["18", "ASSAULT", "攻击"],
    ["180", "Assault, not specified below", "攻击，未特指"],
    ["181", "Conduct armed attack", "进行武装攻击"],
    ["182", "Conduct aerial bombing", "进行空中轰炸"],
    ["183", "Conduct artillery shelling", "进行炮击"],
    ["184", "Conduct a terrorist attack", "进行恐怖袭击"],
    ["185", "Assassinate", "暗杀"],
    ["19", "FIGHT", "战斗"],
    ["190", "Fight, not specified below", "战斗，未特指"],
    ["191", "Engage in small-scale fighting", "进行小规模战斗"],
    ["192", "Engage in large-scale fighting", "进行大规模战斗"],
    ["193", "Engage in aerial warfare", "进行空战"],
    ["194", "Engage in naval warfare", "进行海战"],
    ["195", "Use weapons of mass destruction", "使用大规模杀伤性武器"],
    ["20", "USE UNCONVENTIONAL MASS VIOLENCE", "使用非常规大规模暴力"],
    ["200", "Use unconventional mass violence, not specified below", "使用非常规大规模暴力，未特指"],
    ["201", "Conduct a chemical weapons attack", "进行化学武器攻击"],
    ["202", "Conduct a biological weapons attack", "进行生物武器攻击"],
    ["203", "Conduct a nuclear weapons attack", "进行核武器攻击"]
]

# 保存
save_dir = r"C:\Users\胡克劳\Desktop\GDELT"
os.makedirs(save_dir, exist_ok=True)  # 自动创建不存在的文件夹
save_path = os.path.join(save_dir, "gdelt_event_codes.csv")

# 创建DataFrame并导出CSV
df = pd.DataFrame(data, columns=["Event Code", "English Description", "Chinese Explanation"])
df.to_csv(save_path, index=False, encoding="utf-8-sig")

print(f"CSV文件已生成：{save_path}")
